config:
  COM_PORT: AUTO
  THEME: Default
  HW_SENSORS: PYTHON
  ETH: Ethernet
  WLO: ''
  CPU_FAN: AUTO
  PING: 8.8.8.8
  WEATHER_API_KEY: ''
  WEATHER_LATITUDE: 19.43
  WEATHER_LONGITUDE: -99.13
  WEATHER_UNITS: metric
  WEATHER_LANGUAGE: es
  WEATHER_CITY: ''
display:
  REVISION: A
  BRIGHTNESS: 70
  DISPLAY_ORIENTATION: portrait
  DISPLAY_REVERSE: false
  RESET_ON_STARTUP: false
  ECO_MODE: true
  SKIP_UNCHANGED_FRAMES: true
