#Requires -Version 5.1
<#
.SYNOPSIS
  lcd-monitor-mini: write VERSION into packaging + app markers.

.PARAMETER Version
  SemVer X.Y.Z (default: read ./VERSION)
#>
param(
    [string]$Version = ""
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$versionFile = Join-Path $root "VERSION"

if (-not $Version) {
    if (-not (Test-Path $versionFile)) {
        throw "VERSION file not found: $versionFile"
    }
    $Version = (Get-Content $versionFile -Raw).Trim()
}

if ($Version -notmatch '^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$') {
    throw "Invalid version (expected X.Y.Z): '$Version'"
}

$major = [int]$Matches.major
$minor = [int]$Matches.minor
$patch = [int]$Matches.patch

# Keep VERSION file in sync when -Version is passed explicitly.
[System.IO.File]::WriteAllText($versionFile, $Version)

$issPath = Join-Path $root "packaging\lcd-monitor-mini.iss"
$iss = Get-Content -Path $issPath -Raw -Encoding UTF8
$iss2 = [regex]::Replace($iss, '(?m)^#define MyAppVersion\s+".*"\s*$', "#define MyAppVersion `"$Version`"")
if ($iss2 -eq $iss -and $iss -notmatch [regex]::Escape("#define MyAppVersion `"$Version`"")) {
    throw "Could not update MyAppVersion in $issPath"
}
[System.IO.File]::WriteAllText($issPath, $iss2)

$viPath = Join-Path $root "packaging\version_info.txt"
$vi = @"
# UTF-8
#
# Fixed file info for lcd-monitor-mini.exe (generated by scripts/sync-version.ps1)
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=($major, $minor, $patch, 0),
    prodvers=($major, $minor, $patch, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [
            StringStruct(u'CompanyName', u'lcd-monitor-mini'),
            StringStruct(u'FileDescription', u'lcd-monitor-mini - USB serial LCD system monitor'),
            StringStruct(u'FileVersion', u'$Version'),
            StringStruct(u'InternalName', u'lcd-monitor-mini'),
            StringStruct(u'LegalCopyright', u''),
            StringStruct(u'OriginalFilename', u'lcd-monitor-mini.exe'),
            StringStruct(u'ProductName', u'lcd-monitor-mini'),
            StringStruct(u'ProductVersion', u'$Version'),
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"@
[System.IO.File]::WriteAllText($viPath, $vi.TrimStart() + "`n")

$initPath = Join-Path $root "app\__init__.py"
$init = Get-Content -Path $initPath -Raw -Encoding UTF8
$init2 = [regex]::Replace($init, '(?m)^__version__\s*=\s*["''].*["'']\s*$', "__version__ = `"$Version`"")
if ($init2 -eq $init -and $init -notmatch [regex]::Escape("__version__ = `"$Version`"")) {
    throw "Could not update __version__ in $initPath"
}
[System.IO.File]::WriteAllText($initPath, $init2)

Write-Host "Synced version $Version -> VERSION, packaging\, app\__init__.py"
Write-Output $Version
